# This workflow is triggered manually from the GitHub UI.
name: Manual Docker Build and Push

# Use the workflow_dispatch event to allow manual triggering
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag (e.g., 1.0.0 or latest)'
        required: true
        default: 'latest'

# A single job to build and push the image
jobs:
  build-and-push:
    # Runs on the latest version of Ubuntu
    runs-on: ubuntu-latest

    # Steps to be executed in the job
    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          # Your Docker Hub username stored in a GitHub Secret
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          # Your Docker Hub Personal Access Token stored in a GitHub Secret
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Step 3: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # Enable BuildKit (a newer, faster build engine)
          push: true
          # The context is the current directory
          context: .
          # Path to your Dockerfile, if it's not in the root
          file: ./arc-backend/Dockerfile
          # Tags the image with the specified username, name, and the tag from the manual input
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/arc-backend:1.0

